### PR TITLE
Daniel

### PR DESCRIPTION
**Pull request by dkim157**
Pull request for collab data changes that weren't merged

### CODE REVIEW

**Review by emilyytruong — COMMENTED** [review]
Changes look good to me

**Comment by dkim157** [comment]
> awesome thank you!

**Comment by jhtranx** [comment]
Great work with the backend. I cant wait for the top featured artists to be displayed in the front end :0)

**Comment by dkim157** [comment]
> Great work with the backend. I cant wait for the top featured artists to be displayed in the front end :0)

Thanks I really appreciate it! I can't wait either and we can finally have our infinite artist exploring

**Comment by jettcost38** [comment]
Everything checks out with me. Outstanding work!

**Comment by dkim157** [comment]
> Everything checks out with me. Outstanding work!

Thanks jett!

**Pull request merged**
