### PR TITLE
jett play button

### PR DESCRIPTION
**Pull request by jettcost38**
spotify play buttons embedded into react table in the frontend.

### CODE REVIEW

**Comment by dkim157** [comment]
awesome stuff! can't wait to implement along with the code design!

**Comment by jettcost38** [comment]
> awesome stuff! can't wait to implement along with the graphic design!

Thanks Daniel! Loving the whole Spotify integration process!

**Comment by emilyytruong** [comment]
The play button looks great and it works well! Keep up the great work!

**Comment by jhtranx** [comment]
Looks good! Thank you for your service to this team

**Comment by jettcost38** [comment]
> The play button looks great and it works well! Keep up the great work!

Thank you Emily! Always appreciate your hard work and dedication!

**Comment by jettcost38** [comment]
> Looks good! Thank you for your service to this team

Thanks so much Justin! No you :)

**Pull request merged**
